### ISSUE TITLE
server-side timer sounds not emitted

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#1058]

**Comment by jflamy** [comment]
This exception is now appearing. No changes were made in that area, so what indirect effect is causing this remains to be found.
```
18:23:44.705 ERROR could not emit /sounds/finalWarning.wav java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)
	at app.owlcms.sound.WaveFileReader.getFMT(WaveFileReader.java:208)
	at app.owlcms.sound.WaveFileReader.getAudioInputStream(WaveFileReader.java:156)
	at app.owlcms.sound.Sound.emit(Sound.java:58)
	at app.owlcms.fieldofplay.FieldOfPlay.emitFinalWarning(FieldOfPlay.java:1430)
	at app.owlcms.fieldofplay.ProxyAthleteTimer.finalWarning(ProxyAthleteTimer.java:52)
	at app.owlcms.fieldofplay.ProxyAthleteTimer$2.run(ProxyAthleteTimer.java:196)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
 [app.owlcms.sound.Sound:77 emit]
```
