### ISSUE TITLE
Error start on linux

### ISSUE THREAD

**Issue by eldina07** [jflamy/owlcms4#182]
Hello!

I try to use owlcms on Linux, but i have an error:

Log:
`10:24:57.681 INFO  owlcms 4.1.19 built 2019-09-30 20:04:21 (America/Montreal)                  [app.owlcms.Main:245 logStart]
10:24:57.782 INFO  Database: jdbc:h2:file:./database/owlcms;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=4, inMemory=false, reset=false [app.owlcms.Main:213 processSettings]
10:24:59.384 INFO  database not empty: Competition ?                                           [app.owlcms.Main:228 injectData]
10:24:59.438 INFO  starting web server                                                         [app.owlcms.Main:48 run]
10:24:59.519 WARN  Can't generate resourceBase as part of webapp tmp dir name: java.lang.NullPointerException [org.eclipse.jetty.webapp.WebInfConfiguration:794 getCanonicalNameForWebAppTmpDir]
10:24:59.571 WARN  Failed startup of context o.e.j.w.WebAppContext@5b39a3e6{/,jar:file:/home/aeldin/ows/owlcms.jar!/META-INF/resources/,UNAVAILABLE} [org.eclipse.jetty.webapp.WebAppContext:533 doStart]
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:445)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:361)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:172)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:101)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at app.owlcms.init.EmbeddedJetty.run(EmbeddedJetty.java:76)
	at app.owlcms.Main.main(Main.java:60)
10:24:59.581 INFO  started on port 8080                                                        [app.owlcms.Main:77 run]`

I don't known why i have this error. I try with different release, it's same. File permissions? It's same when I launch with sudo mode.

Ubuntu 18.04.3 LTS and i have openjdk-8

**Comment by jflamy** [comment]
I will check Linux after releasing 4.1.20 which fixes a bug with buttons.

Le jeu. 3 oct. 2019 à 04:29, Eldin Arnaud <notifications@github.com> a
écrit :

**Comment by jflamy** [comment]
Should be fixed in 4.2.20-beta7

- Tested under a new 18.03 setup
- I installed adoptopenjdk according to instructions at https://adoptopenjdk.net/installation.html#linux-pkg
- I got an error about the canberra-gtk module not being found on my machine, which I fixed with https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed

![VirtualBox_Ubuntu1803_05_10_2019_12_05_56](https://user-images.githubusercontent.com/678663/66257551-bf15c200-e768-11e9-88f0-186d2b4d078f.png)

**Comment by jflamy** [comment]
Release process was breaking the packaging for linux (development version was being packaged instead of the free-standing production version).  4.2.0-beta8 should fix.

**Comment by jflamy** [comment]
Just checked that release 4.1.20 is correct as well.
