### ISSUE TITLE
absence of i18n local should not be an error when owlcms configures publicresults

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#761]
```
08:14:28.864 ERROR FOP A    missing remote configuration https://fhq-results.fly.dev/update HTTP/1.1 412 Precondition Failed (Thread.java:833) [app.owlcms.monitors.EventForwarder:773 doPost]
08:14:28.864 INFO  FOP A    sending config                                                     [app.owlcms.monitors.EventForwarder:1115 sendConfig]
08:14:28.864 ERROR java.nio.file.NoSuchFileException: ..\shared\src\main\resources\i18n

...

	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:232)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:283)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:329)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
	at app.owlcms.utils.ResourceWalker.getResourceListFromPath(ResourceWalker.java:788)
```

**Comment by jflamy** [comment]
Seems to have been fixed by other changes to the interaction between the programs
