### ISSUE TITLE
Pre-competition Teams Document Generation Failure

### ISSUE THREAD

**Issue by scottgonzalez** [jflamy/owlcms4#792]
**Describe the bug**
Attempting to down the Teams document from the Pre-competition Documents page fails. An empty file is generated and the download dialog remains open.

**owlcms version**
version 4.44.0

**To Reproduce**
1. Go to 'Pre-compeition Documents'
2. Click on 'Team'
3. See error

**Expected behavior**
The Teams document is generated and the dialog closes.

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Browser Brave 1.52.122

**Additional context**
```
19:02:59.816 DEBUG (1) curTemplateName Teams-LETTER.xls                                        [app.owlcms.components.DownloadDialog:128 createDialog]
19:02:59.817 DEBUG (1) template found /Users/scottgonzalez/Desktop/collective_classic/owlcms/local/templates/teams/Teams-LETTER.xls [app.owlcms.components.DownloadDialog:131 createDialog]
19:02:59.834 DEBUG (2) template found /Users/scottgonzalez/Desktop/collective_classic/owlcms/local/templates/teams/Teams-LETTER.xls [app.owlcms.components.DownloadDialog:149 lambda$createDialog$f195998b$1]
19:02:59.834 DEBUG (2) template as set Teams-LETTER.xls                                        [app.owlcms.components.DownloadDialog:151 lambda$createDialog$f195998b$1]
19:02:59.834 DEBUG (2) template as stored Teams-LETTER.xls                                     [app.owlcms.components.DownloadDialog:155 lambda$createDialog$f195998b$1]
19:02:59.835 DEBUG (2) filter present = M1 null null                                           [app.owlcms.components.DownloadDialog:159 lambda$createDialog$f195998b$1]
19:02:59.835 DEBUG (2) targetFileName final = teams_M1_2023-11-01_19h02;59.xls                 [app.owlcms.components.DownloadDialog:163 lambda$createDialog$f195998b$1]
19:03:01.055 ERROR java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.TreeMap.put(TreeMap.java:809)
	at java.base/java.util.TreeMap.put(TreeMap.java:534)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at net.sf.jxls.util.ReportUtil.groupCollectionData(ReportUtil.java:79)
	at net.sf.jxls.tag.ForEachTag.process(ForEachTag.java:206)
	at net.sf.jxls.transformer.TagRowTransformer.transform(TagRowTransformer.java:32)
	at net.sf.jxls.transformer.SheetTransformer.transformSheet(SheetTransformer.java:94)
	at net.sf.jxls.transformer.XLSTransformer.transformWorkbook(XLSTransformer.java:261)
	at net.sf.jxls.transformer.XLSTransformer.transformXLS(XLSTransformer.java:234)
	at app.owlcms.spreadsheet.JXLSWorkbookStreamSource.writeStream(JXLSWorkbookStreamSource.java:381)
	at app.owlcms.spreadsheet.JXLSWorkbookStreamSource.accept(JXLSWorkbookStreamSource.java:99)
	at com.vaadin.flow.server.communication.StreamResourceHandler.handleRequest(StreamResourceHandler.java:86)
	at com.vaadin.flow.server.communication.StreamRequestHandler.handleRequest(StreamRequestHandler.java:110)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1529)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
 [app.owlcms.spreadsheet.JXLSWorkbookStreamSource:38 logError]
```

**Comment by jflamy** [comment]
Does the team management page work ?

**Comment by scottgonzalez** [comment]
The team management page loads fine and displays all of the teams and athletes.

**Comment by scottgonzalez** [comment]
Database export:
[owlcmsDatabase_2023-11-01_21h12.json](https://github.com/jflamy/owlcms4/files/13233095/owlcmsDatabase_2023-11-01_21h12.json)
