### ISSUE TITLE
v44.7 cloud deployment : publicresults send config error

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#818]
owlcms not locating i18n translation directory correctly when bundling the information for publicresults.

```
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]15:42:49.243 INFO  FOP A    sending config
                          [app.owlcms.monitors.EventForwarder:1115 sendConfig]
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]15:42:49.248 ERROR java.nio.file.NoSuchFileException: ../shared/src/main/resources/i18n
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/java.nio.file.Files.readAttributes(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/java.nio.file.FileTreeWalker.getAttributes(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/java.nio.file.FileTreeWalker.visit(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/java.nio.file.FileTreeWalker.walk(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at app.owlcms.utils.ResourceWalker.getResourceListFromPath(ResourceWalker.java:791)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at app.owlcms.utils.ResourceWalker.addToResourceMap(ResourceWalker.java:672)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at app.owlcms.utils.ResourceWalker.getPRResourceMap(ResourceWalker.java:648)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at app.owlcms.utils.ResourceWalker.zipPublicResultsConfig(ResourceWalker.java:398)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at app.owlcms.monitors.EventForwarder.lambda$sendConfig$2(EventForwarder.java:1126)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info]     at java.base/java.lang.Thread.run(Unknown Source)
2023-12-27T15:42:49Z app[4d891375b02498] yyz [info] [app.owlcms.utils.ResourceWalker:38 logError]
```

**Comment by jflamy** [comment]
In a cloud deployment without a local override, should be searching inside the jar itself, using the zip file system, and not using the Linux file system.

**Comment by jflamy** [comment]
Works fine in v45. Won't fix.
