### ISSUE TITLE
i18n glitch with publicresults

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#839]
Wishful thinking that this was gone.
```
16:38:22.126 INFO  FOP B    sending config
16:38:22.129 ERROR java.nio.file.NoSuchFileException: ..\shared\src\main\resources\i18n
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:201)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:232)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:283)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:329)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
        at app.owlcms.utils.ResourceWalker.getResourceListFromPath(ResourceWalker.java:794)
        at app.owlcms.utils.ResourceWalker.addToResourceMap(ResourceWalker.java:675)
        at app.owlcms.utils.ResourceWalker.getPRResourceMap(ResourceWalker.java:651)
        at app.owlcms.utils.ResourceWalker.zipPublicResultsConfig(ResourceWalker.java:401)
        at app.owlcms.monitors.EventForwarder.lambda$sendConfig$2(EventForwarder.java:1128)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jflamy** [comment]
Fixed the exception catch clause;
