### ISSUE TITLE
Cannot load custom AgeGroups file

### ISSUE THREAD

**Issue by endwaa** [jflamy/owlcms4#897]
**Describe the bug**
Loading custom AgeGroups file is failing (see stack trace below).

**owlcms version**
version 47.1.2 (working in 44.4.0)

**Additional context**

[AgeGroups_NOR.xlsx](https://github.com/jflamy/owlcms4/files/14963473/AgeGroups_NOR.xlsx)

```
20:27:16.516 INFO  loading age group configuration file /agegroups/AgeGroups_NOR.xlsx
20:27:16.519 INFO  loading age group definitions /agegroups/AgeGroups_NOR.xlsx
20:27:16.526 ERROR could not process ageGroup configuration
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell
	at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1035)
	at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:390)
	at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:342)
	at app.owlcms.data.agegroup.AgeGroupDefinitionReader.lambda$createAgeGroups$1(AgeGroupDefinitionReader.java:86)
	at app.owlcms.data.jpa.JPAService.runInTransaction(JPAService.java:234)
	at app.owlcms.data.agegroup.AgeGroupDefinitionReader.createAgeGroups(AgeGroupDefinitionReader.java:50)
	at app.owlcms.data.agegroup.AgeGroupDefinitionReader.loadAgeGroupStream(AgeGroupDefinitionReader.java:216)
	at app.owlcms.data.agegroup.AgeGroupDefinitionReader.doInsertRobiAndAgeGroups(AgeGroupDefinitionReader.java:188)
	at app.owlcms.data.agegroup.AgeGroupRepository.reloadDefinitions(AgeGroupRepository.java:399)
	at app.owlcms.nui.preparation.AgeGroupContent.lambda$createMenuArea$2(AgeGroupContent.java:147)
	at app.owlcms.components.ConfirmationDialog.lambda$new$3ac6cc7e$1(ConfirmationDialog.java:38)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:488)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:298)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:466)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$4(ServerRpcHandler.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:447)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:324)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1574)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:838)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:463)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:761)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:597)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:424)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1201)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1156)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by jflamy** [comment]
Ok. In version 47 there is no longer a tab for Robi world records.
That tab was assumed to be the first one.
In the _NOR spreadsheet, it had been moved to the second one.
The detection of the old format was based on the number of tabs -- if 2, old format, read second tab as the groups file.
I have fixed the file so it works with version 48.
About to test that it works in version 47 as well.

**Comment by jflamy** [comment]
I need to retrofit a couple changes from 48 into 47 to make things a bit more robust.  You can try with version 48 beta 04 or better, or wait for the fixed 47.

**Comment by jflamy** [comment]
https://github.com/owlcms/owlcms4-prerelease/releases/tag/47.1.3-rc01 includes the forward compatibility with version 48.
The simplified AgeGroups_NOR.xlsx file that should work with both is attached.

[AgeGroups_NOR.xlsx](https://github.com/jflamy/owlcms4/files/14964235/AgeGroups_NOR.xlsx)

**Comment by jflamy** [comment]
The only change in 47.1.3-rc01 is related to the age groups.  The version should be fine for a competition if needed.  I will build the stable version once this is confirmed to work.

**Comment by jflamy** [comment]
I removed the Robi world records tab (so the resulting file has only one tab). I also removed the gender letters in columns H and above (they were redundant and error-prone -- this is the retrofit from version 48.

**Comment by endwaa** [comment]
Very good! Did a simple test and it seems to work perfectly. Thank you.
